# Generated by Django 3.2.4 on 2023-02-23 08:33

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('text', models.CharField(max_length=10000)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='images')),
            ],
            options={
                'verbose_name': 'Articles',
            },
        ),
    ]
