# Generated by Django 3.2.4 on 2023-02-23 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_articles_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name_plural': 'Articles'},
        ),
    ]
